name: Build and push Docker image
on:
  push:
    branches: [ "develop" ]
#  pull_request:
#    branches: [ "develop" ]
env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/govsso-client:develop
jobs:
  build:
    name: Build
    permissions:
      packages: write
#      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build
      run: mvn --batch-mode --update-snapshots -Dspring-boot.build-image.imageName=$IMAGE_NAME dependency:tree spring-boot:build-image

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Maven Dependency Tree Dependency Submission
    #  uses: advanced-security/maven-dependency-submission-action@v3
    #Error: HTTP Status 403 for request POST https://api.github.com/repos/alarkvell/GOVSSO-Client/dependency-graph/snapshots
    #Error: Response body:
    #  "message": "Resource not accessible by integration",
    #  "documentation_url": "https://docs.github.com/rest/reference/dependency-graph#create-a-snapshot-of-dependencies-for-a-repository"

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

# docker/metadata-action -- tag?

    - name: Push Docker image
      run: docker push $IMAGE_NAME
